// Starter systems and habits to seed new users.
const systems = [
  { id: 'system-morning', name: 'Morning Routine', description: 'Anchors to start the day right', color: '#F97316', icon: '☀️' },
  { id: 'system-body', name: 'Body', description: 'Movement, strength, recovery', color: '#22C55E', icon: '🏋️' },
  { id: 'system-intelligence', name: 'Intelligence', description: 'Learning and practice', color: '#6366F1', icon: '🧠' },
  { id: 'system-career', name: 'Career Growth', description: 'Skills and research', color: '#F59E0B', icon: '💼' },
  { id: 'system-reset', name: 'Human Reset', description: 'Recovery and maintenance', color: '#0EA5E9', icon: '💧' },
];

const habits = [
  {
    id: 'habit-vitamins',
    systemId: 'system-morning',
    name: 'Vitamins',
    purpose: 'Body',
    timeBlock: 'Morning',
    frequency: { type: 'daily' },
    durationMinutes: 2,
    notes: 'Take with water after waking',
    startDate: '2024-01-01',
  },
  {
    id: 'habit-sunlight',
    systemId: 'system-morning',
    name: 'Sunlight',
    purpose: 'Body',
    timeBlock: 'Morning',
    frequency: { type: 'daily' },
    durationMinutes: 8,
    notes: 'Walk outside, no sunglasses for 8-10 minutes',
    startDate: '2024-01-01',
  },
  {
    id: 'habit-stretch',
    systemId: 'system-body',
    name: 'Stretch routine',
    purpose: 'Body',
    timeBlock: 'Evening',
    frequency: { type: 'daysOfWeek', daysOfWeek: [1, 3, 5] },
    durationMinutes: 15,
    notes: 'Hip flexors + hamstrings floor stretch',
    startDate: '2024-01-01',
  },
  {
    id: 'habit-gym',
    systemId: 'system-body',
    name: 'Gym',
    purpose: 'Body',
    timeBlock: 'Midday',
    frequency: { type: 'daysOfWeek', daysOfWeek: [1, 3, 5] },
    durationMinutes: 60,
    notes: 'Push / Pull / Legs rotation',
    startDate: '2024-01-01',
  },
  {
    id: 'habit-duolingo',
    systemId: 'system-intelligence',
    name: 'Spanish learning (Duolingo)',
    purpose: 'Intelligence',
    timeBlock: 'Morning',
    frequency: { type: 'daily' },
    durationMinutes: 10,
    notes: '1 lesson, focus on speaking aloud',
    startDate: '2024-01-01',
  },
  {
    id: 'habit-datacamp',
    systemId: 'system-intelligence',
    name: 'DataCamp learning',
    purpose: 'Intelligence',
    timeBlock: 'Evening',
    frequency: { type: 'everyXDays', intervalDays: 2 },
    durationMinutes: 25,
    notes: 'Analytics or SQL course progress',
    startDate: '2024-01-01',
  },
  {
    id: 'habit-career-research',
    systemId: 'system-career',
    name: 'Career research',
    purpose: 'Money',
    timeBlock: 'Midday',
    frequency: { type: 'daysOfWeek', daysOfWeek: [2, 4] },
    durationMinutes: 30,
    notes: 'Market scan, target roles, and outreach notes',
    startDate: '2024-01-01',
  },
  {
    id: 'habit-laser',
    systemId: 'system-reset',
    name: 'Laser session',
    purpose: 'Body',
    timeBlock: 'Evening',
    frequency: { type: 'everyXDays', intervalDays: 7 },
    durationMinutes: 20,
    notes: 'Home device weekly session',
    startDate: '2024-01-01',
  },
  {
    id: 'habit-retainers',
    systemId: 'system-reset',
    name: 'Retainers',
    purpose: 'Body',
    timeBlock: 'Evening',
    frequency: { type: 'daily' },
    durationMinutes: 1,
    notes: 'Clean and wear overnight',
    startDate: '2024-01-01',
  },
  {
    id: 'habit-nails',
    systemId: 'system-reset',
    name: 'Nails care',
    purpose: 'Home',
    timeBlock: 'Midday',
    frequency: { type: 'everyXDays', intervalDays: 10 },
    durationMinutes: 15,
    notes: 'Trim, file, moisturize',
    startDate: '2024-01-01',
  },
];

export default { systems, habits };
